# Problem 2:
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first  terms will be: 1,2,3,5,8,13,21,34,55,89.
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
Input Format
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer,N .
Output Format
Print the required answer for each test case.
Sample Input 0
2
10
100
Sample Output 0
10
44
Explanation 0
For N=10, we have {2,8}, sum is 10.
For , N= 100,we have {2,8,34}, sum is 44.
'''

t = int(input().strip())
for a0 in range(t):
  n = int(input().strip())
  fib= []
  fib1= []
  a0 = 1
  a1 = 2
  Sum = 0
  fib.append(a0)
  fib.append(a1)
  fib1.append(a1)
  while Sum < n:
    Sum = a0+a1
    if Sum < n: # There was one last extra term coming. So added this.
      fib.append(Sum)
    if Sum%2 == 0 and Sum < n: # There was one last extra term coming. So added this.
      fib1.append(Sum)
    a0 = a1
    a1= Sum
  #print(fib)
  print(sum(fib1))


#or
t = int(input().strip())
for a0 in range(t):
  n = int(input().strip())
  fib= []
  fib1= []
  a0 = 1
  a1 = 2
  Sum = 0
  fib.append(a0)
  fib.append(a1)
  fib1.append(a1)
  while Sum < n:
    Sum = a0+a1
    if Sum < n: # There was one last extra term coming. So added this.
      fib.append(Sum)
    if Sum%2 == 0 and Sum < n: # There was one last extra term coming. So added this.
      fib1.append(Sum)
    a0 = a1
    a1= Sum
  #print(fib)
  print(sum(fib1))
